spring.application.name=forhos

spring.datasource.url=jdbc:mysql://localhost:3306/forhos?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&createDatabaseIfNotExist=true
spring.datasource.username=${DB_USERNAME:ssafy}
spring.datasource.password=${DB_PASSWORD:ssafy}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=${JWT_SECRET:fb81881510ce7b9460a7b0e13a55c1d6682aba4a0db1eab2f1e29afe1cfda94b}
jwt.access-token-expiration=3600000
